server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.25.96.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/   
