server:
  port: 9001

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.host.docker.internal:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

spring:
  boot:
    admin:
      client:
        url:
          - http://host.docker.internal:1111/  # Admin service URL pointing to host.docker.internal

logging:
  level:
    com.netflix.discovery: DEBUG  # Enables debug logging for Eureka discovery to troubleshoot issues
    org.springframework.cloud.netflix: DEBUG
